"""catalog_overrides

Revision ID: 27e9554f4946
Revises: 95c862132eaf
Create Date: 2026-08-25 23:14:52.232287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27e9554f4946'
down_revision: Union[str, Sequence[str], None] = '95c862132eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_overrides',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_key', sa.String(length=64), nullable=True),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('changed_by', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverted_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_overrides_active', 'catalog_overrides', ['reverted_at', 'id'], unique=False)
    op.create_index(op.f('ix_catalog_overrides_path'), 'catalog_overrides', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_overrides_path'), table_name='catalog_overrides')
    op.drop_index('ix_catalog_overrides_active', table_name='catalog_overrides')
    op.drop_table('catalog_overrides')
    # ### end Alembic commands ###
