"""baseline schema

Revision ID: 8a38abd49cd8
Revises: 
Create Date: 2026-08-24 14:24:46.792940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a38abd49cd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('item_id', sa.String(length=128), nullable=True),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Enum('new', 'qualifying', 'quoted', 'lead_captured', 'escalated', 'closed', name='chat_state'), nullable=False),
    sa.Column('is_human_takeover', sa.Boolean(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('agent_reply_count', sa.Integer(), nullable=False),
    sa.Column('takeover_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_msg_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=True)
    op.create_index(op.f('ix_chats_item_id'), 'chats', ['item_id'], unique=False)
    op.create_table('concession_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dialog_id', sa.String(length=128), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=255), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('revenue_delta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('revenue_delta_basis', sa.String(length=32), nullable=True),
    sa.Column('exchange_given', sa.String(length=64), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('provisional_policy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concession_log_dialog_id'), 'concession_log', ['dialog_id'], unique=False)
    op.create_table('item_zone_map',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_zone_map_item_id'), 'item_zone_map', ['item_id'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_chat_id'), 'leads', ['chat_id'], unique=False)
    op.create_table('operator_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_actions_chat_id'), 'operator_actions', ['chat_id'], unique=False)
    op.create_table('zone_service_map',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=True),
    sa.Column('staff_id', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_service_map_zone_id'), 'zone_service_map', ['zone_id'], unique=True)
    op.create_table('dialog_states',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('base_price_quoted', sa.Boolean(), nullable=False),
    sa.Column('used_tiers', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('skipped_tiers', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('floor_reached', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('client_constraints', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('concessions_count', sa.Integer(), nullable=False),
    sa.Column('touch_count', sa.Integer(), nullable=False),
    sa.Column('last_touch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_touch_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialog_states_chat_id'), 'dialog_states', ['chat_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.Enum('incoming', 'outgoing', name='direction'), nullable=False),
    sa.Column('author', sa.Enum('client', 'agent', 'operator', name='author'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('image_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('avito_message_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'dry_run', 'failed', 'rejected', name='send_status'), nullable=False),
    sa.Column('llm_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avito_message_id', name='uq_messages_avito_message_id')
    )
    op.create_index('ix_messages_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index('ix_messages_chat_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_dialog_states_chat_id'), table_name='dialog_states')
    op.drop_table('dialog_states')
    op.drop_index(op.f('ix_zone_service_map_zone_id'), table_name='zone_service_map')
    op.drop_table('zone_service_map')
    op.drop_index(op.f('ix_operator_actions_chat_id'), table_name='operator_actions')
    op.drop_table('operator_actions')
    op.drop_index(op.f('ix_leads_chat_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_item_zone_map_item_id'), table_name='item_zone_map')
    op.drop_table('item_zone_map')
    op.drop_index(op.f('ix_concession_log_dialog_id'), table_name='concession_log')
    op.drop_table('concession_log')
    op.drop_index(op.f('ix_chats_item_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###

    # Ручная правка после autogenerate: DROP TABLE не убирает Postgres ENUM
    # типы, на которые ссылались колонки (chat_state/direction/author/
    # send_status) — autogenerate их тоже не генерирует сам, это известный
    # пробел инструмента с именованными enum-типами Postgres. Без этого
    # блока downgrade оставляет типы висеть в БД, и повторный upgrade падает
    # на CREATE TYPE ... DuplicateObjectError — воспроизведено и проверено
    # на пустой parmangal_test.
    sa.Enum(name='chat_state').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='direction').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='author').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='send_status').drop(op.get_bind(), checkfirst=True)
