"""concession moderation columns on pending_replies

Revision ID: 95c862132eaf
Revises: cb8196de34b1
Create Date: 2026-08-25 16:57:33.407815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c862132eaf'
down_revision: Union[str, Sequence[str], None] = 'cb8196de34b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default добавлен вручную: колонка NOT NULL без него падает на
    # ADD COLUMN, если в pending_replies уже есть строки на момент деплоя
    # (живая очередь модерации DRY_RUN) — autogenerate этого не увидел,
    # потому что тестовая база, с которой сравнивалась схема, пустая.
    op.add_column(
        'pending_replies',
        sa.Column('is_concession', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('pending_replies', sa.Column('fallback_text', sa.Text(), nullable=True))
    op.add_column('pending_replies', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_replies', 'due_at')
    op.drop_column('pending_replies', 'fallback_text')
    op.drop_column('pending_replies', 'is_concession')
    # ### end Alembic commands ###
